CC = gcc
CFLAGS = -Wall

all: for_loops conditionals while_loops functions hello

for_loops:
	$(CC) $(CFLAGS) -o for_loops for_loops.c

conditionals:
	$(CC) $(CFLAGS) -o conditionals conditionals.c

while_loops:
	$(CC) $(CFLAGS) -o while_loops while_loops.c

functions:
	$(CC) $(CFLAGS) -o functions functions.c

hello:
	$(CC) $(CFLAGS) -o hello hello.c

clean:
	rm for_loops conditionals while_loops functions hello

